local native = require("den.native")
local actions = require("den.actions")

T.test("the engine loads in Neovim", function()
  local mod = native.need()
  T.ok(mod.version():match("^%d+%.%d+%.%d+$"), "a version")
  T.ok(mod.ready(), "ready after load")
end)

T.test("Tasks for all projects shows doing first, then each project", function()
  require("den.screens.tasks").open({ all = true })
  local lines = T.lines()
  T.contains(lines[1], "Tasks · all projects")
  T.contains(lines, "  doing")
  T.contains(lines, "Wire up the renderer")
  T.contains(lines, "  Personal website")
  T.contains(lines, "Ask two friends to read the draft", "a linked note's task shows under its project")
  T.lacks(lines, "Never going to happen", "archived projects stay out")
  T.lacks(lines, "Sketch the desk layout", "paused projects stay out")
  T.contains(lines[#lines], "s start")
end)

T.test("Tasks for one project shows only that project", function()
  require("den.screens.tasks").open({ project = "haste" })
  local lines = T.lines()
  T.contains(lines[1], "Tasks · haste")
  T.contains(lines, "Profile the first frame")
  T.lacks(lines, "Choose three projects")
end)

T.test("x finishes a task in its file and s starts one with the timer", function()
  require("den.screens.tasks").open({ project = "website" })
  local row = T.item("tasks", "Choose three projects to feature")
  actions.done(row)
  local today = native.call("today")
  T.contains(T.read("projects/website.md"), "- [x] Choose three projects to feature #writing @done(" .. today .. ")")
  T.lacks(T.lines(), "○  Choose three projects", "it left the open list")

  local refs = T.item("tasks", "Gather a few visual references")
  actions.start(refs)
  T.contains(T.read("projects/website.md"), "- [/] Gather a few visual references")
  local running = native.call("timer_running")
  T.eq(running and running.task, "Gather a few visual references", "the timer runs on it")
  actions.pause()
  T.eq(native.call("timer_running"), nil, "paused")
  T.contains(T.read("projects/website.md"), "- [/] Gather a few visual references", "still doing after a pause")
end)

T.test("the Inbox lists captures and > makes one a next action", function()
  require("den.screens.inbox").open()
  local lines = T.lines()
  T.contains(lines[1], "Inbox")
  T.contains(lines, "Call the printer about the proofs")
  T.contains(lines, "Idea: a lamp for the reference shelf")
  local row = T.item("inbox", "Call the printer about the proofs")
  require("den.screens.inbox").keys[">"][1](row)
  local text = T.read("projects/haste.md")
  T.contains(text, "- [x] Sketch the lua_module surface @done(2026-09-24)\n- [ ] Call the printer about the proofs\n")
  T.lacks(T.lines(), "Call the printer about the proofs", "it left the inbox")
end)

T.test("capture lands in the project's inbox", function()
  T.ok(require("den.capture").save("Order more paper", "haste"))
  T.contains(T.read("projects/haste.md"), "- [ ] Order more paper\n")
end)

T.test("capture outside a project uses the general inbox", function()
  T.ok(require("den.capture").save("Buy stamps", false))
  T.contains(T.read("inbox.md"), "- [ ] Buy stamps\n")
end)

T.test("the capture box saves on enter", function()
  local buf, win = require("den.capture").open({ project = "website" })
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "Typed into the box" })
  vim.api.nvim_set_current_win(win)
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<CR>", true, false, true), "x", false)
  T.contains(T.read("projects/website.md"), "- [ ] Typed into the box\n")
  T.ok(not vim.api.nvim_win_is_valid(win), "the box closed")
end)
