local native = require("den.native")
local statusline = require("den.statusline")

T.test("the statusline shows the timer, then the two most urgent things", function()
  vim.cmd.cd(T.tmp)
  native.call("timer_stop")
  statusline.refresh()
  T.eq(statusline.text(), "1 overdue  Gather a few visual ref… · due today  Profile the first frame")
end)

T.test("a running timer comes first and its clock ticks", function()
  native.call("timer_start", "projects/haste.md", "Wire up the renderer")
  statusline.refresh()
  local text = statusline.text(1)
  T.ok(text:match("^◐ Wire up the renderer  00:0%d · 1 overdue"), text)
  T.contains(statusline.string(1), "%#DenStatusTimer#")
  native.call("timer_stop")
  statusline.refresh()
  T.lacks(statusline.text(), "◐")
end)

T.test("extra sources compete for the insight places by priority", function()
  statusline.register("test-nudge", "insight", 10, function()
    return { text = "go outside", hl = "DenNudge" }
  end)
  statusline.register("test-sync", "status", 1, function()
    return { text = "↑ 2 to sync", hl = "DenSync" }
  end)
  statusline.refresh()
  T.eq(statusline.text(), "go outside · 1 overdue  Gather a few visual ref… · ↑ 2 to sync")
  statusline.register("test-nudge", "insight", 10, function() end)
  statusline.register("test-sync", "status", 1, function() end)
end)

T.test("percent signs in task titles cannot break the statusline", function()
  local apply = require("den.apply")
  apply.run(function(mod)
    return mod.plan_add("haste", "Hit 100% coverage", "next_actions")
  end)
  native.call("timer_start", "projects/haste.md", "Hit 100% coverage")
  statusline.refresh()
  T.contains(statusline.string(0), "Hit 100%% coverage")
  native.call("timer_stop")
end)
